notifications:
  webhooks:
    - https://discordapp.com/api/webhooks/517358922873700352/cr40fi6gMrlRBsXRJQAIwOlesJUGORiaRIcZ58lLadlyq_QiZI0yAT0UhWLw63lWQq6C

services:
  - docker

script:
  - docker build --build-arg steam_username=$STEAM_USERNAME --build-arg steam_password=$STEAM_PASSWORD -t sourceforts/dedicated-server:debian-$TRAVIS_BUILD_NUMBER -t sourceforts/dedicated-server:debian -t sourceforts/dedicated-server:latest .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: bash .travisci/deploy.sh
  on:
    branch: master