services:
  - docker

script:
  - pushd ubuntu-xenial
  - docker build --build-arg steam_username=$STEAM_USERNAME --build-arg steam_password=$STEAM_PASSWORD -t pistonsh/srcds-server:ubuntu-xenial-$TRAVIS_BUILD_NUMBER .
  - docker tag pistonsh/srcds-server:ubuntu-xenial-$TRAVIS_BUILD_NUMBER pistonsh/srcds-server:ubuntu-xenial
  - docker tag pistonsh/srcds-server:ubuntu-xenial-$TRAVIS_BUILD_NUMBER pistonsh/srcds-server:ubuntu
  - docker tag pistonsh/srcds-server:ubuntu-xenial-$TRAVIS_BUILD_NUMBER pistonsh/srcds-server:latest
  - popd

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: bash .travisci/deploy.sh
  on:
    branch: master

after_success:
  - ./.travisci/send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - ./.travisci/send.sh failure $DISCORD_WEBHOOK_URL
