services:
  - docker

script:
  - docker build --build-arg steam_username=$STEAM_USERNAME --build-arg steam_password=$STEAM_PASSWORD -t sourceforts/dedicated-server:debian-$TRAVIS_BUILD_NUMBER -t sourceforts/dedicated-server:debian -t sourceforts/dedicated-server:latest .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script:
    - docker push sourceforts/dedicated-server:debian-$TRAVIS_BUILD_NUMBER
    - docker push sourceforts/dedicated-server:debian
    - docker push sourceforts/dedicated-server:latest
  on:
    branch: master

deploy:
  provider: script
  script: bash .travisci/deploy.sh
  on:
    branch: master